### ISSUE TITLE
Handle Pagination

### ISSUE THREAD

**Issue by ryanjagar** [ryanjagar/epi-data#4]
The Proof application paginates [form query](https://github.com/proofgov/api/blob/master/forms-endpoints.md) responses.  The paginations parameters are, to some extent, configurable. 

This application should gracefully handle the configuration and parsing of paginated responses.

**Comment by leeomara** [comment]
Inspecting a result from the query endpoint shows that useful pagination information is returned.

```
{
  data: [...],
  meta: {
    pagination: {
      current_page: 1,
      total_pages: 338,
      total_count: 3374,
      per_page: 10
    }
  }
```

How lovely!
